name: Build and publish to Docker hub

on:
  workflow_dispatch:
  # push:
      #branches: [ "main" ]
 

jobs:

  build-and-push-to-docker-hub:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      id: build
      run: docker build . --file Dockerfile --tag mustafakeles/nginx-app:$(date +%s)
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
    - run: docker push ${{ steps.build.output }}
  
