name: Docker latest

on:
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Upload a Build Artifact  
      uses: actions/upload-artifact@v3.1.1
      with:
    # Artifact name
        name: webapp-1 # optional, default is artifact
      # A file, directory or wildcard pattern that describes what to upload
        path: mustafa-keles/nginx-app
